[features]
resolution = true
skip-lint = false

[programs.localnet]
head_to_head = "J5D34or7JDTnQFvCX8PpiAbkoYrYAhza3Xczi28PZR8p"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "signer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
